test fix: do not access content directly
"TSError: ⨯ Unable to compile TypeScript:
spec/services/import/single.spec.ts:137:25 - error TS2339: Property 'content' does not exist on type 'BNote'."